name: Build

on:
  push:
    branches:
      - 'main'
      - 'bobko/**'
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *' # every day at 00:00

jobs:
  build:
    strategy:
      matrix:
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md
        os: [macos-13, macos-14]
    name: Build
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: .bin
          key: ${{ runner.os }}-${{ runner.arch }}
      - name: Install deps
        run: brew bundle install
      - name: Build Debug
        # "-" means "Sign to run locally". There is no aerospace-codesign-certificate in GH Actions
        run: ./build-debug.sh --codesign-identity -
      - name: Test
        run: ./run-tests.sh
      - name: Build Release
        run: ./build-release.sh --codesign-identity -
